name: UpdateTODO

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      new_version:
        description: 'new project version'
        required: true
        default: 'warning'

jobs:
  test-logs-files:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Run check of pwd
      run: pwd
    - name: Run check of what's in pwd
      run: ls
    - name: Run a one-line script
      run: python ./.github/workflows/todo_List.py '${{github.event.inputs.new_version}}'
    - name: check for changes
      run: git status
    - name: stage changed files
      run: git add .
    - name: github email
      run: git config user.email "vicente.coves@scopely.com" 
    - name: github name
      run: git config user.name "VicenteCoves"
    - name: commit changed files
      run: git commit -m "Auto updating TODO.txt"
    - name: fetch from master
      run: git fetch origin master
    - name: push code to master
      run: git push origin HEAD:master
    
      
      
